require: rubocop-rspec
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Exclude:
    - 'config/environments/*'
Style/MixinUsage:
  Exclude:
    - 'db/seeds.rb'
    - 'bin/*'
Documentation:
  Enabled: false
Style/RegexpLiteral:
  AllowInnerSlashes: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/matchers/*'
RSpec/DescribeClass:
  Exclude:
    - 'spec/matchers/*'