require: rubocop-rspec
AllCops:
  Exclude:
    - 'db/migrate/*'
Documentation:
  Enabled: false
Style/RegexpLiteral:
  AllowInnerSlashes: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
