require: rubocop-rspec
AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
Documentation:
  Enabled: false
Style/RegexpLiteral:
  AllowInnerSlashes: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
Style/MixinUsage:
  Exclude:
    - 'db/seeds.rb'